### ISSUE TITLE
Fastly

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems-infrastructure#30]
# Fastly
## Phase 1 - Initial setup on Fastly domain (`rubygems.global.ssl.fastly.net`)
- [x] Use Fastly to deliver .gem files from CloudFront
  Ref: https://github.com/rubygems/rubygems-infrastructure/commit/1e21eb2f467364b60a96a361ac2e0f8c684facf1
- [x] Remove old mirrors, only use Fastly
  Ref: https://github.com/rubygems/rubygems-infrastructure/commit/b80a15662d7e5d6b743f7eca8cbc3df1231d8c27
  Ref: https://github.com/rubygems/rubygems-infrastructure/commit/21293b9fc2fee79b97ad9a148bbe4cc1c3ddf9db
## Phase 2 - Move more assets to Fastly
- [x] Update Fastly to use S3 as the origin directly, removing CloudFront
- [x] Update LB nginx config to use Fastly for legacy (static) index files
  Ref: https://github.com/rubygems/rubygems-infrastructure/commit/0df840d2dc62258b1975ef3827ec32fda642d223
- [x] Use Fastly for full index files. This also requires purges from the app when the index files change.
  Ref: https://github.com/rubygems/rubygems-infrastructure/commit/a6e3bdb41cf110bbf14c861c6bbd19f83574aa80
  Ref: https://github.com/rubygems/rubygems.org/pull/1036
## Phase 3 - Use Fastly for primary domain (rubygems.org)
- [x] Provision SSL for `rubygems.org` and `*.rubygems.org`
- [x] Move stats processing to new process (Fastly logs pushed to S3, background processing into redis) #35 
- [x] Setup logging
- [x] Configure Fastly to route to the 3 backends properly
  - [x] .gem downloads to S3
  - [x] current Bundler API
  - [x] new versions API to bundler_api
  - [x] rubygems client downloads to S3
  - [x] everything else to rails
- [x] Update app config to purge both services
- [x] Test app caching, do we need to purge anything else? - probably start with as little caching as possible so we can gradually increase

**Comment by nateberkopec** [comment]
Will we get [automatic gzipping](https://docs.fastly.com/guides/basic-configuration/enabling-automatic-gzipping) on rubygems.org?

**Comment by dwradcliffe** [comment]
@nateberkopec We can definitely look at enabling it eventually but probably not initially.

**Comment by nateberkopec** [comment]
:+1: I'll investigate trying to get it configured correctly in Sprockets/Rails then, looks like some assets aren't being gzipped correctly.
